### PR TITLE
deptai_bridge/urdf.launch error in file stereo_inertial_node.launch

### PR DESCRIPTION
**Pull request by Mky07**
I would like to share with you a problem I encountered. Maybe you add the solution in required packages. We can run multiple cameras by giving different mxid to "depthai_examples stereo_inertial_node.launch". However, when you run more than one camera, it gave an error in the line which involes "urdf.launch" in the launch. I fix this error by grouping it . I used "tf_prefix" params but mxID could be better. Check file.
```
    <group ns="$(arg tf_prefix)">
        <include file="$(find depthai_bridge)/launch/urdf.launch">
            <arg name="base_frame" value="$(arg  base_frame)" />
            <arg name="parent_frame" value="$(arg  parent_frame)"/>
            <arg name="camera_model" value="$(arg  camera_model)"/>
            <arg name="tf_prefix" value="$(arg  tf_prefix)" />
            <arg name="cam_pos_x" value="$(arg  cam_pos_x)" />
            <arg name="cam_pos_y" value="$(arg  cam_pos_y)" />
            <arg name="cam_pos_z" value="$(arg  cam_pos_z)" />
            <arg name="cam_roll" value="$(arg  cam_roll)" />
            <arg name="cam_pitch" value="$(arg  cam_pitch)" />
            <arg name="cam_yaw" value="$(arg  cam_yaw)" />
        </include>
    </group>
```
[stereo_inertial_node.zip](https://github.com/luxonis/depthai-ros-examples/files/9077993/stereo_inertial_node.zip)
.

### CODE REVIEW

**Comment by saching13** [comment]
1. I am not sure why you are creating a PR between two branches. 

Soln for your problem would be to is just create a multiple launches of stereo_inertial_node.launch to your own launch file. 
If you need keep each one of the under the group_ns you need (I think this is needed to properly map the topic names). 


```
    <group ns="$(arg tf_prefix)">

  <include file="$(find depthai_examples)/launch/stereo_inertial_node.launch">
            <arg name="tf_prefix" value="left_camera" />
            <arg name="mx_id" value="1930403443" />
        </include>
    </group>

```

**Comment by Mky07** [comment]
I am doing pull request for the first time. So it happened by mistake.
Yours is a solution too. However, this should always be done from all of the people used this package. So I think it's better to add this in the package by default.
The problem here is that when multiple "stereo_inertial_node.launch" is run, the "robot_description" parameter in the "dephai_bridge/launch/urdf.launch" package is used multiple times. This also causes an error. That's why I only grouped the " ...urdf.launch" line in this package. I think this process can be fixed in "dephai_bridge/launch/urdf.launch" or added to "stereo_inertial_node.launch" by default.

**Comment by saching13** [comment]
> I am doing pull request for the first time. So it happened by mistake. Yours is a solution too. However, this should always be done from all of the people used this package. So I think it's better to add this in the package by default. The problem here is that when multiple "stereo_inertial_node.launch" is run, the "robot_description" parameter in the "dephai_bridge/launch/urdf.launch" package is used multiple times. This also causes an error. That's why I only grouped the " ...urdf.launch" line in this package. I think this process can be fixed in "dephai_bridge/launch/urdf.launch" or added to "stereo_inertial_node.launch" by default.

I agree on the issue when you try to launch it multiple times without grouping. 
But note that if I add grouping inside my file and you add some more nodes which recives from this node and process it then it will not be under that group. you endup making group in exterior again. 

Our launch file is for one device with the capability to launch multiple times when you add it with other perception nodes. 
So the orchestration of how to structure the tree should stay external for better usage, configuration and flexibility.

**Comment by Mky07** [comment]
The problem here was with the "robot_description" param. Once you fixed it, there would be no need for grouping. But if you think it will break any structure, keep it that way.

**Pull request closed without merging**
