### PR TITLE
[noetic] add missing installation steps for the package to be usable in a non devel workspace

### PR DESCRIPTION
**Pull request by mikaelarguedas**
Also fixes some trailing whitespaces and linter violation reported by catkin_lint

### CODE REVIEW

**Comment by Luxonis-Brandon** [comment]
Thanks again.  @saching13

**Comment by saching13** [comment]
Since these are examples I would prefer not to have the option to install this. Thoughts?

**Comment by mikaelarguedas** [comment]
What prompted this PR is  that I dropped this repo in one of my usual workspaces that are always install-enabled. Because none of the examples were installed I couldnt find the nodes/nodelet or use them with my regular "source the install/setup.bash and run stuff" workflow.

Is there a different package that would provide a "standard ROS driver with nodelets" for the OAK-D camera that I could install and use on my robotics system?

**Comment by saching13** [comment]
> What prompted this PR is that I dropped this repo in one of my usual workspaces that are always install-enabled. Because none of the examples were installed I couldnt find the nodes/nodelet or use them with my regular "source the install/setup.bash and run stuff" workflow.

Hhmm. Makes sense. Let me think on this one.

> Is there a different package that would provide a "standard ROS driver with nodelets" for the OAK-D camera that I could install and use on my robotics system?

`depthai-ros` is more like a bridge or interface to the depthai-core which is our C++ library.

Since depthai is a configurable node-based pipeline and there can be many ways the user can build their own pipeline which can be placed as node or nodelet. we don't have much preconfigured nodelets with the driver. 


And `depthai-ros-examples` is just a entry point to run the basic examples we have and test working on your bot.

**Pull request closed without merging**
